sudo: false
language: php

branches:
  except:
    - gh-pages
    - /^circleci-.*$/
    - /^wercker-.*$/

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  - phpize && ./configure && make

script:
  - make test REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TESTS="--show-all" | tee tests-output.txt && if grep -q 'TEST SUMMARY$' tests-output.txt ; then exit 1 ; fi
