sudo: false
language: php

branches:
  except:
    - gh-pages
    - /^circleci-.*$/
    - /^wercker-.*$/

matrix:
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
  allow_failures:
    - php: nightly
  fast_finish: false

before_script:
  - phpize && ./configure && make

script:
  - make test REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TESTS="--show-all" | tee tests-output.txt && if grep -q 'TEST SUMMARY$' tests-output.txt ; then exit 1 ; fi
